### ISSUE TITLE
Timestamps are not ordered

### ISSUE THREAD

**Issue by xaur** [companyzero/zkc#102]
Sometimes timestamp of my contact's reply is lower than of my message. I guess this happens if there is a difference between our clocks, or my clock and the server clock. Not sure about the exact cause, but clearly more than 1 time source is used to set timestamps, which leads to confusing UI.

**Comment by marcopeereboom** [comment]
The server is the one who decides on the timestamp. We do this very much deliberately because we want to make sure the client is not able to manipulate this. A use case is employee tells employer "hey I called in sick at 6am". If we enforce timestamps on the server side we can see if someone is fibbing.

While this is somewhat confusing it is working as designed.

Clocks should be kept in sync via NTP however there are still debates raging if NTP is safe enough to use.

**Comment by xaur** [comment]
Sorry this does not explain why timestamps are not ordered. It looks like the other guys timestamps come from the server while mine are local.
